[project]
name = "gitsh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gitsh",
    "rich>=13.9.4",
    "typer>=0.15.1",
]

[tool.uv.sources]
gitsh = { workspace = true }
